### ISSUE TITLE
Videos won't download

### ISSUE THREAD

**Issue by GabrielAC2019** [ImAiiR/TIDALDownloaderX#1]
I have tried using the latest and older versions of this program, but none work anymore as of two days ago. It used to work before this. Now, I get the following message: 

"Downloading section #0 Job Completed! If not, your session expired. Refresh the TIDAL page, get a new link, & try again!"

I followed the same steps as I usually have done, but now nothing downloads. Additionally, I still do have a Premium account.

**Comment by ImAiiR** [comment]
Just tested it and sure enough it's now happening to me too. Seems they've changed something. I'll look into it as soon as I'm able to.

**Comment by ImAiiR** [comment]
And I believe it should be fixed. Version 1.0.4 is up, so downloading it should fix the issue.
https://github.com/ImAiiR/TIDALDownloaderX/releases/tag/1.0.4
